### ISSUE TITLE
label = category_index[classes[index]]['name']

### ISSUE THREAD

**Issue by mohammadakz** [AndrewCarterUK/tf-example-object-detection-api-race-cars#3]

**Comment by DexterFernandes** [comment]
I am getting the same issue when I try to run annotate.py. Have you been able to solve it?

**Comment by DexterFernandes** [comment]
I have found the solution for this problem. The problem lies with the model that is being used for auto-annotation. 

The author of this project trained his own model on his custom dataset. Therefore, to run detections on objects from the COCO dataset, place any frozen_inference_graph.pb file from the TF model zoo and place the mscoco_label_map.pbtxt file in the data directory and then run annotate.py

To use your own custom models for auto-annotation, place your custom trained model and label_map.pbtxt into the appropriate directories and run annotate.py. You will find your generated .XML annotations in the test directory.

And do not forget to make changes to the PATH_TO_CKPT, PATH_TO_LABELS, NUM_CLASSES and TOTAL_IMAGES in the annotate.py file.
